### ISSUE TITLE
Becoming member of @nodejs

### ISSUE THREAD

**Issue by IonicaBizau** [nodejs/iojs-ro#4]
@mikeal Can I be added member in this organization? @radubrehar added me as collaborator in this repo but I would like to be a member in the `iojs-ro` team as well, so member in this GitHub organization. Thanks! :sparkle:

**Comment by mikeal** [comment]
added :)

**Comment by IonicaBizau** [comment]
@mikeal Thanks! :cake:

**Comment by alrra** [comment]
> 

@mikeal Can I be added member in this organization? @radubrehar added me as collaborator in this repo but I would like to be a member in the iojs-ro team as well, so member in this GitHub organization. Thanks! :sparkle:

> added :)

@mikeal Can the same be done for me? Thanks! :)

**Comment by alrra** [comment]
@mikeal nevermind. :)
